services:
  omnia-music:
    image: ghcr.io/kresnab/omnia-music:latest
    container_name: omnia-music
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    volumes:
      - /home/kresna/omnia-music/storage/audio-cache:/music:ro
      - omnia-data:/app/data

volumes:
  omnia-data:
    driver: local
