services:
  omnia-music:
    build: .
    container_name: omnia-music
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - /home/kresna/omnia-music/storage/audio-cache:/music:ro
      - omnia-data:/app/data
    environment:
      - PORT=3000
      - DB_PATH=/app/data/omnia.db
      - AUDIO_PATH=/music
      - INDEX_PATH=/music/index.json
      - JWT_SECRET=omnia-secret-2026

volumes:
  omnia-data:
    driver: local
