services:
  omnia-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: omnia-bot:local
    container_name: omnia-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage/audio-cache:/config/audio-cache
      - ./storage:/app/storage
      - ./cookies.txt:/config/cookies.txt
